export const DATA_FETCH_START = 'DATA_FETCH_START';
export const DATA_FETCH_SUCCESS = 'DATA_FETCH_SUCCESS';
export const DATA_FETCH_ERROR = 'DATA_FETCH_ERROR';
export const ADD_DATA_ITEM = 'ADD_DATA_ITEM';
export const UPDATE_DATA_ITEM = 'UPDATE_DATA_ITEM';
export const DELETE_DATA_ITEM = 'UPDATE_DATA_ITEM';